---
-
  name: ensure that iptables starts at boot time
  service: name=iptables state=enabled
-
  name: define basic table
  command: bash /mnt/ansible/scripts/firewall_basic.sh
-
  name: restart iptables
  service: name=iptables state=started
