---
- hosts: all
  sudo: true
  tasks:
  remote_user: vagrant
  - name: install misc packages
    apt: name={{ item }} state=present
    with_items:
      - rubygems
      - git-core
      - curl
      - unzip
      - vim
      - zsh
      - ctags

  - include: tasks/dotfiles.yml

  # # sympa
  # - name: create src directory
  #   command: mkdir /vagrant/ansible/src creates=/vagrant/ansible/src

  # - name: download sympa if not present
  #   shell: chdir=/vagrant/ansible/src creates=sympa-6.1.19.tar.gz wget http://www.sympa.org/distribution/sympa-6.1.19.tar.gz

  # # -
  # #   include: tasks/apache.yml

  # - name: create /var/www if not present
  #   file: path=/var/www state=directory

  # - name: create site symlink
  #   file: src=/vagrant dest=/var/www/site state=link
  #   notify: restart apache

  # -
  #   include: tasks/mailman.yml

  # # # Assets compilation

  # # - name: install nodejs
  # #   apt: name=nodejs state=latest

  # # - name: install rubygems
  # #   apt: name=rubygems state=present

  # # - name: install compass
  # #   command: gem install compass sass chunky_png fssm creates=/usr/local/bin/compass



  # # # - name: install npm packages
  # # #   command: chdir=/var/www/site npm install --no-bin-links
  # # #   register: out
  # # #   changed_when: "out.stdout.strip() != ''"
  # # #   sudo: false

  # # # - name: install composer packages
  # # #   command: chdir=/var/www/site bash pocket install
  # # #   register: out
  # # #   changed_when: "'Nothing to install or update' not in out.stdout"
  # # #   sudo: false

  # # # - name: set up artisan queue listen
  # # #   copy: src=/vagrant/ansible/templates/supervisor-queue-listen.conf dest=/etc/supervisor/conf.d/supervisor-queue-listen.conf
  # # #   notify: reload queue listener

  # # # Common stuff

  handlers:
    include: handlers/handlers.yml
