---
-
  hosts: vagrant
  sudo: True
  tasks:
    -
      name: install sshfs
      apt: name=sshfs state=present
    -
      name: mount folder
      raw: sudo sshfs schuppo@`echo $SSH_CLIENT | awk '{ print $1}'`:"/Users/schuppo/Centos 6.5" /mnt -o uid=500 -o gid=500 -o allow_other
      tags: mount
